### ISSUE TITLE
Encountered an interesting issue with vobject. Calling 'v.serialize()' multiple times results in unexpected errors.

### ISSUE THREAD

**Issue by Gerald-Meyers** [py-vobject/vobject#84]
So I was modifying a vcf file I made on my phone and just trying out the vobject module to do so. I was trying to save a file but kept getting type errors pointing back to vobject's base.py.

'Gerald Meyers'
TypeError: a bytes-like object is required, not 'str'
v.serialize() output:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[14], [line 4](vscode-notebook-cell:?execution_count=14&line=4)
      [2](vscode-notebook-cell:?execution_count=14&line=2)     with open(my_card, 'wb') as card:
      [3](vscode-notebook-cell:?execution_count=14&line=3)         # card.write(serialized.encode('utf-8'))
----> [4](vscode-notebook-cell:?execution_count=14&line=4)         card.write(v.serialize().encode('utf-8'))
      [5](vscode-notebook-cell:?execution_count=14&line=5) except TypeError as e:

File c:\ProgramData\miniconda3\lib\site-packages\vobject\base.py:254, in VBase.serialize(self, buf, lineLength, validate, behavior)
    [253](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:253)         logger.debug("serializing {0!s} with behavior {1!s}".format(self.name, behavior))
--> [254](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:254)     return behavior.serialize(self, buf, lineLength, validate)
    [255](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:255) else:

File c:\ProgramData\miniconda3\lib\site-packages\vobject\behavior.py:166, in Behavior.serialize(cls, obj, buf, lineLength, validate)
    [164](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/behavior.py:164)     undoTransform = False
--> [166](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/behavior.py:166) out = base.defaultSerialize(transformed, buf, lineLength)
    [167](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/behavior.py:167) if undoTransform:

File c:\ProgramData\miniconda3\lib\site-packages\vobject\base.py:1007, in defaultSerialize(obj, buf, lineLength)
   [1005](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1005) for child in obj.getSortedChildren():
   [1006](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1006)     # validate is recursive, we only need to validate once
-> [1007](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1007)     child.serialize(outbuf, lineLength, validate=False)
   [1008](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1008) if obj.useBegin:

File c:\ProgramData\miniconda3\lib\site-packages\vobject\base.py:254, in VBase.serialize(self, buf, lineLength, validate, behavior)
    [253](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:253)         logger.debug("serializing {0!s} with behavior {1!s}".format(self.name, behavior))
--> [254](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:254)     return behavior.serialize(self, buf, lineLength, validate)
    [255](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:255) else:

File c:\ProgramData\miniconda3\lib\site-packages\vobject\vcard.py:237, in Photo.serialize(cls, obj, buf, lineLength, validate)
    [236](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/vcard.py:236)     lineLength = REALLY_LARGE
--> [237](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/vcard.py:237) VCardTextBehavior.serialize(obj, buf, lineLength, validate)

File c:\ProgramData\miniconda3\lib\site-packages\vobject\behavior.py:166, in Behavior.serialize(cls, obj, buf, lineLength, validate)
    [164](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/behavior.py:164)     undoTransform = False
--> [166](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/behavior.py:166) out = base.defaultSerialize(transformed, buf, lineLength)
    [167](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/behavior.py:167) if undoTransform:

File c:\ProgramData\miniconda3\lib\site-packages\vobject\base.py:1015, in defaultSerialize(obj, buf, lineLength)
   [1014](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1014) if obj.behavior and not startedEncoded:
-> [1015](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1015)     obj.behavior.encode(obj)
   [1017](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1017) s = six.StringIO()

File c:\ProgramData\miniconda3\lib\site-packages\vobject\vcard.py:161, in VCardTextBehavior.encode(cls, line)
    [160](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/vcard.py:160) else:
--> [161](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/vcard.py:161)     line.value = backslashEscape(line.value)
    [162](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/vcard.py:162) line.encoded = True

File c:\ProgramData\miniconda3\lib\site-packages\vobject\base.py:1219, in backslashEscape(s)
   [1218](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1218) def backslashEscape(s):
-> [1219](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1219)     s = s.replace("\\", "\\\\").replace(";", "\;").replace(",", "\,")
   [1220](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1220)     return s.replace("\r\n", "\\n").replace("\n", "\\n").replace("\r", "\\n")

TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
Cell In[14], [line 8](vscode-notebook-cell:?execution_count=14&line=8)
      [6](vscode-notebook-cell:?execution_count=14&line=6) print(f"TypeError: {e}")
      [7](vscode-notebook-cell:?execution_count=14&line=7) print("v.serialize() output:")
----> [8](vscode-notebook-cell:?execution_count=14&line=8) print(v.serialize())

File c:\ProgramData\miniconda3\lib\site-packages\vobject\base.py:254, in VBase.serialize(self, buf, lineLength, validate, behavior)
    [252](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:252)     if DEBUG:
    [253](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:253)         logger.debug("serializing {0!s} with behavior {1!s}".format(self.name, behavior))
--> [254](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:254)     return behavior.serialize(self, buf, lineLength, validate)
    [255](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:255) else:
    [256](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:256)     if DEBUG:

File c:\ProgramData\miniconda3\lib\site-packages\vobject\behavior.py:166, in Behavior.serialize(cls, obj, buf, lineLength, validate)
    [163](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/behavior.py:163)     transformed = obj
    [164](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/behavior.py:164)     undoTransform = False
--> [166](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/behavior.py:166) out = base.defaultSerialize(transformed, buf, lineLength)
    [167](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/behavior.py:167) if undoTransform:
    [168](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/behavior.py:168)     obj.transformToNative()

File c:\ProgramData\miniconda3\lib\site-packages\vobject\base.py:1007, in defaultSerialize(obj, buf, lineLength)
   [1003](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1003)     foldOneLine(outbuf, "{0}BEGIN:{1}".format(groupString, obj.name),
   [1004](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1004)                 lineLength)
   [1005](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1005) for child in obj.getSortedChildren():
   [1006](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1006)     # validate is recursive, we only need to validate once
-> [1007](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1007)     child.serialize(outbuf, lineLength, validate=False)
   [1008](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1008) if obj.useBegin:
   [1009](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1009)     foldOneLine(outbuf, "{0}END:{1}".format(groupString, obj.name),
   [1010](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1010)                 lineLength)

File c:\ProgramData\miniconda3\lib\site-packages\vobject\base.py:254, in VBase.serialize(self, buf, lineLength, validate, behavior)
    [252](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:252)     if DEBUG:
    [253](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:253)         logger.debug("serializing {0!s} with behavior {1!s}".format(self.name, behavior))
--> [254](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:254)     return behavior.serialize(self, buf, lineLength, validate)
    [255](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:255) else:
    [256](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:256)     if DEBUG:

File c:\ProgramData\miniconda3\lib\site-packages\vobject\vcard.py:237, in Photo.serialize(cls, obj, buf, lineLength, validate)
    [235](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/vcard.py:235) if wacky_apple_photo_serialize:
    [236](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/vcard.py:236)     lineLength = REALLY_LARGE
--> [237](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/vcard.py:237) VCardTextBehavior.serialize(obj, buf, lineLength, validate)

File c:\ProgramData\miniconda3\lib\site-packages\vobject\behavior.py:166, in Behavior.serialize(cls, obj, buf, lineLength, validate)
    [163](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/behavior.py:163)     transformed = obj
    [164](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/behavior.py:164)     undoTransform = False
--> [166](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/behavior.py:166) out = base.defaultSerialize(transformed, buf, lineLength)
    [167](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/behavior.py:167) if undoTransform:
    [168](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/behavior.py:168)     obj.transformToNative()

File c:\ProgramData\miniconda3\lib\site-packages\vobject\base.py:1015, in defaultSerialize(obj, buf, lineLength)
   [1013](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1013) startedEncoded = obj.encoded
   [1014](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1014) if obj.behavior and not startedEncoded:
-> [1015](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1015)     obj.behavior.encode(obj)
   [1017](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1017) s = six.StringIO()
   [1019](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1019) if obj.group is not None:

File c:\ProgramData\miniconda3\lib\site-packages\vobject\vcard.py:161, in VCardTextBehavior.encode(cls, line)
    [159](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/vcard.py:159)         line.value = codecs.encode(line.value.encode(encoding), "base64").decode("utf-8")
    [160](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/vcard.py:160) else:
--> [161](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/vcard.py:161)     line.value = backslashEscape(line.value)
    [162](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/vcard.py:162) line.encoded = True

File c:\ProgramData\miniconda3\lib\site-packages\vobject\base.py:1219, in backslashEscape(s)
   [1218](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1218) def backslashEscape(s):
-> [1219](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1219)     s = s.replace("\\", "\\\\").replace(";", "\;").replace(",", "\,")
   [1220](file:///C:/ProgramData/miniconda3/lib/site-packages/vobject/base.py:1220)     return s.replace("\r\n", "\\n").replace("\n", "\\n").replace("\r", "\\n")

TypeError: a bytes-like object is required, not 'str'
vobject.base.ContentLine

**Comment by da4089** [comment]
Thanks for the report!

It'd be helpful to know:
* the version of Python in use
* the version of vObject in use
* the operating system

and if possible,
* a copy of the vCard the triggers the error
* a short Python program that exhibits the issue

I tried:

```
import vobject

with open("test_files/vcard_with_groups.ics") as f:
    s = vobject.readOne(f)

c = vobject.readOne(s)
c.serialize().encode("utf-8")
c.serialize().encode("utf-8")
c.serialize().encode("utf-8")
```

but that works fine, so I imagine I'm missing something ...

**Comment by aaschmid** [comment]
I have the same problem on MacOS, tested with Python 3.10 and 3.12. `vobject` version is 0.9.8. Both is installed via `nix`.

```
  File "[...]/main.py", line 291, in _write
    card.serialize(buf=f)
  File "/nix/store/xz4l2h7q23i9azfjqdhwd6q0zsyzyl6n-python3.12-vobject-0.9.8/lib/python3.12/site-packages/vobject/base.py", line 264, in serialize
    return behavior.serialize(self, buf, lineLength, validate, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/xz4l2h7q23i9azfjqdhwd6q0zsyzyl6n-python3.12-vobject-0.9.8/lib/python3.12/site-packages/vobject/behavior.py", line 167, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/xz4l2h7q23i9azfjqdhwd6q0zsyzyl6n-python3.12-vobject-0.9.8/lib/python3.12/site-packages/vobject/base.py", line 1066, in defaultSerialize
    child.serialize(outbuf, lineLength, validate=False)
  File "/nix/store/xz4l2h7q23i9azfjqdhwd6q0zsyzyl6n-python3.12-vobject-0.9.8/lib/python3.12/site-packages/vobject/base.py", line 264, in serialize
    return behavior.serialize(self, buf, lineLength, validate, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/xz4l2h7q23i9azfjqdhwd6q0zsyzyl6n-python3.12-vobject-0.9.8/lib/python3.12/site-packages/vobject/behavior.py", line 167, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/xz4l2h7q23i9azfjqdhwd6q0zsyzyl6n-python3.12-vobject-0.9.8/lib/python3.12/site-packages/vobject/base.py", line 1093, in defaultSerialize
    foldOneLine(outbuf, s.getvalue(), lineLength)
  File "/nix/store/xz4l2h7q23i9azfjqdhwd6q0zsyzyl6n-python3.12-vobject-0.9.8/lib/python3.12/site-packages/vobject/base.py", line 1034, in foldOneLine
    outbuf.write(to_unicode(s))
TypeError: a bytes-like object is required, not 'str'
```

Also haven't looked deeper into it, maybe one of the new cards is broken or something else on my local machine causes the issue ...

**Comment by aaschmid** [comment]
Debugged my code, and it seems that only two cards were affected. Still couldn't find what the problem is. I am very sure that I created the contacts on my Pixel phone and synced that to my Contact app. But also changing the card in my Contact app manually hasn't solved my issue. Here is the code I use:

```
my_contacts = _load_contacts(my_contacts_dir, debug)
for path, card in my_contacts.items():
    changed = False
    if "," in card.fn.value:
        changed = True
        split = card.fn.value.split(",")
        card.fn.value = f"{split[1].strip()} {split[0].strip()}"

    if changed:
        if debug:
            print(f"Changed card for {card.getChildValue('fn')} (path: {path}).")
        _write(card, path)

def _write(card: Component, path: Path):
    with path.open("wb") as f:
        card.serialize(buf=f)
```

This is an anonymized version of the card which I try to adjust:
```
BEGIN:VCARD
VERSION:3.0
FN:Surname\, Firstname
N:Surname;Firstname;;;
ADR;TYPE=work,postal,parcel:;;Street str. 13\, 12345 City\, Deutschland;;;;
TEL;TYPE=cell,voice:+49 123 456789
REV:2024-12-30T19:08:21Z
UID:4fa3280a-cdd7-4aad-9fa6-bc797b1fff1f:1077539
END:VCARD
```

**Comment by da4089** [comment]
Thanks for this info @aaschmid!

I am able to reproduce the issue.  For reference, my test case code is below.

```
import vobject

vobject_0084_card = \
    r"BEGIN:VCARD" "\r\n" \
    r"VERSION:3.0" "\r\n" \
    r"FN:Surname\, Firstname" "\r\n" \
    r"N:Surname;Firstname;;;" "\r\n" \
    r"ADR;TYPE=work,postal,parcel:;;Street str. 13\, 12345 City\, Deutschland;;;;" "\r\n" \
    r"TEL;TYPE=cell,voice:+49 123 456789" "\r\n" \
    r"REV:2024-12-30T19:08:21Z" "\r\n" \
    r"UID:4fa3280a-cdd7-4aad-9fa6-bc797b1fff1f:1077539" "\r\n" \
    r"END:VCARD" "\r\n"


def test_vobject_0084():
    card = vobject.readOne(vobject_0084_card)
    with open("/tmp/vobject_0084_card.txt", "wb") as f:
        card.serialize(buf=f)
```

**Comment by da4089** [comment]
This appears to be a symptom of an internal confusion between bytes and string, a consequence of vObject's origins before Python3.  There's little clarity or consistency in internal APIs as to whether values should be in encoded or decoded form, and lots of hacky conversions between them if they're not what's expected at any particular point.

I'm working on this, but I expect it'll take a few days to sort it out.

**Comment by da4089** [comment]
One question: is there a reason you're both opening the output file using the "wb" mode?

If the output stream is opened with the "b" flag, it's a byte stream, and you cannot write string objects to it.  This is the immediate cause of the error: serialise() expects to be able to write strings.

A file opened (for writing) with the "w" (not "wb") mode is in text mode, which will accept strings, and use an implicit codec to convert them to UTF-8 on disc.

**Comment by aaschmid** [comment]
No there is no specific reason to use `wb` mode. Using `w` as mode makes it work. Thanks for the quick response and fix. 

As this change already fixes the problem, you can close my point of the issue. I just changed my code accordingly :-)

Only strange thing is that it has worked with the above code before, even though I cannot tell which versions of python and vobject I used at the time being...

**Comment by da4089** [comment]
I haven't checked, but I think Python 2.x would have worked.

**Comment by aaschmid** [comment]
But it is [sunsetted](https://www.python.org/doc/sunset-python-2/) ;-)

**Comment by rsb-23** [comment]
Using a stream seems consistent with the code.
I am using a [get_buffer function](https://github.com/rsb-23/vobjectx/blob/main/vobject/helper/config.py) to always return a stream.

**Comment by da4089** [comment]
The problem is more whether it's a byte stream or a string stream.

I'm not sure what the correct decision should be here.

Most of the time, it can be UTF8, and everyone will be happy.  The API can accept string types, and read/write string streams.  This should probably be the default, since all recent vObject specifications require UTF8.

But it's possible for a vObject to be transported via a MIME part with a non-UTF8 CHARSET parameter on its Content-Type header, and its also legal for eg. vCard 2.1 cards to have non-UTF character encodings on a per-card or even per-property level (see sections 2.1.5 and 2.1.6 of the vCard 2.1 specification).  iCalendar 2.0 explicitly allows a Content-Type CHARSET parameter too (RFC-5545 s3.1.4).  In those cases, it is necessary to use bytes objects, byte streams, and binary modes on files.

So ... I'm not sure what the best approach is here.  Suggestions?

**Comment by aaschmid** [comment]
Hard decision to make. 

From a user perspective I think, that a clear documentation would be most important. I would also not mind a list of use cases which are not supported.

That being said, I would implement what is easiest and feels most consistent, even though it does not support all possible features and circumstances :-)

**Comment by rsb-23** [comment]
I think string will be better for the main logic, modify as we go on.

To be sure, 
- we can add tests and validate
- study vobject packages in different languages.

**Comment by da4089** [comment]
Having thought about this a little more, given that it's legal in some of the specs we need to support, to have different lines using different character encodings _in the same file_, that we have no alternative but to use `bytes` to hold the whole object value.

Given the common use of `str`, we will obviously need to support it both as input, and where the data allows it, as export.

As @rsb-23 suggested (thank you) I agree: I will track down some test cases, and have a look at what other libraries do here.  It's possible that they ignore the problem (like vobject kinda does today).

**Comment by da4089** [comment]
Note to self: base.py's `foldOneLine()` has a couple of "py2" commented lines relevant to this issue.
